import { SCHEMA_VERSION, makeEvidenceRef, makeFieldEvidence } from "./evidence.mjs";

export function normalizeEvent(raw) {
  return {
    schema_version: SCHEMA_VERSION,
    event_id: raw.event_id || null,
    agent_object: raw.agent_object || null,
    installation_id: raw.installation_id || null,
    adapter_version: raw.adapter_version || null,
    agent_version: raw.agent_version || null,
    session_id: raw.session_id || null,
    root_session_id: raw.root_session_id || null,
    parent_session_id: raw.parent_session_id || null,
    turn_id: raw.turn_id || null,
    step_id: raw.step_id || null,
    llm_call_id: raw.llm_call_id || null,
    attempt_id: raw.attempt_id || null,
    call_id: raw.call_id || null,
    message_id: raw.message_id || null,
    evaluation_run_id: raw.evaluation_run_id || null,
    task_id: raw.task_id || null,
    trial_id: raw.trial_id || null,
    binding_status: raw.binding_status || "unbound",
    trace_id: raw.trace_id || null,
    span_id: raw.span_id || null,
    parent_span_id: raw.parent_span_id || null,
    event_category: raw.event_category || "other",
    event_subtype: raw.event_subtype || null,
    event_type_raw: raw.event_type_raw || null,
    occurred_at: raw.occurred_at || null,
    received_at: raw.received_at || null,
    source_seq: raw.source_seq ?? null,
    timestamp_basis: raw.timestamp_basis || "unknown",
    precision_ms: raw.precision_ms ?? null,
    status: raw.status || "unknown",
    requested_model: raw.requested_model || null,
    routed_model: raw.routed_model || null,
    provider: raw.provider || null,
    tool_name: raw.tool_name || null,
    tool_kind: raw.tool_kind || "unknown",
    skill_name: raw.skill_name || null,
    tool_kind_basis: raw.tool_kind_basis || null,
    usage_record_ids: raw.usage_record_ids || [],
    cost_record_ids: raw.cost_record_ids || [],
    evidence_refs: raw.evidence_refs || [],
    field_evidence: raw.field_evidence || makeFieldEvidence({}),
    metadata: raw.metadata || {},
  };
}

export function normalizeSession(raw) {
  return {
    agent_object: raw.agent_object || null,
    installation_id: raw.installation_id || null,
    session_id: raw.session_id || null,
    root_session_id: raw.root_session_id || null,
    parent_session_id: raw.parent_session_id || null,
    project_dir: raw.project_dir || null,
    title: raw.title || null,
    model: raw.model || null,
    agent_name: raw.agent_name || null,
    started_at: raw.started_at || null,
    ended_at: raw.ended_at || null,
    duration_ms: raw.duration_ms ?? null,
    source_status: raw.source_status || "unknown",
    tokens: raw.tokens || null,
    cost: raw.cost ?? null,
    max_context: raw.max_context ?? null,
    step_count: raw.step_count ?? null,
    llm_call_count: raw.llm_call_count ?? null,
    llm_attempt_count: raw.llm_attempt_count ?? null,
    llm_retry_count: raw.llm_retry_count ?? null,
    tool_call_count: raw.tool_call_count ?? null,
    tool_retry_count: raw.tool_retry_count ?? null,
    human_confirm_count: raw.human_confirm_count ?? null,
    compaction_count: raw.compaction_count ?? null,
    event_counts: raw.event_counts || {
      "llm.request": 0, "llm.response": 0,
      "tool.call": 0, "tool.result": 0,
      "agent.input": 0, other: 0,
    },
    failure_attribution: raw.failure_attribution || {
      gateway: 0, tool: 0, model: 0, dependency: 0, agent: 0,
    },
    data_completeness: raw.data_completeness || null,
    turn_ids: raw.turn_ids || [],
    child_session_ids: raw.child_session_ids || [],
    coverage: raw.coverage || null,
  };
}

export function normalizeUsageRecord(raw) {
  return {
    usage_record_id: raw.usage_record_id || null,
    scope: raw.scope || null,
    scope_id: raw.scope_id || null,
    input: raw.input ?? null,
    output: raw.output ?? null,
    reasoning: raw.reasoning ?? null,
    cache_read: raw.cache_read ?? null,
    cache_write: raw.cache_write ?? null,
    reported_total: raw.reported_total ?? null,
    credits: raw.credits ?? null,
    monetary_cost: raw.monetary_cost ?? null,
    cost_unit: raw.cost_unit || null,
    input_includes_cache: raw.input_includes_cache ?? "unknown",
    output_includes_reasoning: raw.output_includes_reasoning ?? "unknown",
    cache_write_accounting: raw.cache_write_accounting ?? "unknown",
    token_semantics_version: raw.token_semantics_version || null,
    evidence_refs: raw.evidence_refs || [],
  };
}
